# [variant selection]
CLONAL_SNV_THR: 0.90    # Double [0,1]. default = 0.9
MINOR_SNV_SEL: 'always' # String {'always', 'all'}. default = 'always'
MAX_SNV_SAMPLE: 100     #  Integer [1, Inf]. default = 100
MIN_SNV_SAMPLE: 6       # Integer [1, Inf]. default = 6

# [Analysis parameters]
NUM_CONTEXTS: 6         # Integer {6, 96}. default = 6
MIN_NUM_SIG: 1          # Integer [1, NUM_CONTEXTS]. default = 1
MAX_NUM_SIG: 6          # Integer [MIN_NUM_SIG, NUM_CONTEXTS]. default = 6
NMF_ITER: 100           # Integer [1, inf]. default = 100

# [Other]
SEED: 0                 #  Integer [0, Inf]. default =  0 (with 0 the seed will be set randomly)
N_CORE: 0               #  Integer [0, Inf]. default = 0 (with 0 the number of core available will automatically detected)

